### ISSUE TITLE
可以禁用编辑功能吗

### ISSUE THREAD

**Issue by javaxiaobai** [YiJiuSmile/kkFileViewOfficeEdit#1]

**Comment by javaxiaobai** [comment]
只是把这种方式当作文件预览使用，应该这个组件的文件预览功能excel文件排版错乱

**Comment by YiJiuSmile** [comment]
你到web的pom里把pageOffice的引用注释掉吧，那个OnlineEditController也一并注释掉看看
`<dependency> 
<groupId>com.zhuozhengsoft</groupId> 
<artifactId>zhuozhengsoft</artifactId> 
<version>4.5.0.6</version> 
<scope>system</scope> 
<systemPath>${project.basedir}/src/main/resources/lib/pageoffice4.5.0.6.jar</systemPath> 
</dependency>`

**Comment by javaxiaobai** [comment]
OnlineEditController 也注释掉？

**Comment by javaxiaobai** [comment]
pageOffice需要序列号注册

**Comment by YiJiuSmile** [comment]
对，因为里面有类依赖于这个lib
标准版试用序列号：4PGHC-EMHT-UNZW-DZ4IF

专业版试用序列号：V925K-G5RS-4AC8-H3VHC

标准版试用序列号：1PHD2-JVFX-7VV6-DULQ9

专业版试用序列号：QZ4LF-W74G-4MZZ-3Y769

企业版试用序列号：862M8-FVJ4-PRSU-MCS4X

**Comment by javaxiaobai** [comment]
序列号，都不行

**Comment by YiJiuSmile** [comment]
> 只是把这种方式当作文件预览使用，因为这个组件的文件预览功能excel文件排版错乱



> 序列号，都不行

PageOffice V4.0 标准版试用序列号：IMTG6-BSXJ-JGZ6-3BIWM
PageOffice V4.0 专业版试用序列号：CA1XB-MF7Y-12ST-PSBP2
试试这两个
