### ISSUE TITLE
mac下运行报错

### ISSUE THREAD

**Issue by itmyhome** [YiJiuSmile/kkFileViewOfficeEdit#2]
officeHome must exist and be a directory
起初以为是路径中存在空格原因，去除空格也不可以
office.home = classpath:/src/main/resources/OpenOfficePortable/Bin/OpenOffice4

**Comment by YiJiuSmile** [comment]
> officeHome must exist and be a directory
> 起初以为是路径中存在空格原因，去除空格也不可以
> office.home = classpath:/src/main/resources/OpenOfficePortable/Bin/OpenOffice4

更新下代码
